-- Group: Christopher Bragg, William Roe

-- Drop tables, cascade constraints
DROP TABLE Model CASCADE CONSTRAINTS;
DROP TABLE Paint CASCADE CONSTRAINTS;
DROP TABLE Address CASCADE CONSTRAINTS;
DROP TABLE Part CASCADE CONSTRAINTS;
DROP TABLE Bicycle CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Store CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE Component CASCADE CONSTRAINTS;
DROP TABLE Purchase CASCADE CONSTRAINTS;

-- Green Tables
CREATE TABLE Model (
    MODELID NUMBER,
    MODELTYPE VARCHAR2(50),
    PRIMARY KEY (MODELID)
);

CREATE TABLE Paint (
    PAINTID NUMBER(38,0),
    COLORNAME VARCHAR2(50),
    COLORSTYLE VARCHAR(50),
    COLORLIST VARCHAR(50),
    DATEINTRODUCED DATE,
    DATEDISCONTINUED DATE,
    PRIMARY KEY (PAINTID)
);

CREATE TABLE Address (
    ADDRESSID NUMBER(38, 0),
    ADDRESS VARCHAR2(50),
    CITY VARCHAR2(50),
    STATE VARCHAR2(50),
    ZIP VARCHAR2(50),
    COUNTRY VARCHAR2(50),
    PRIMARY KEY (ADDRESSID)
);

CREATE TABLE Part (
    PARTID NUMBER(38,0),
    PARTNAME VARCHAR2(50),
    MANUFACTURERNAME VARCHAR2(50),
    DESCRIPTION VARCHAR2(100),
    LISTPRICE NUMBER(38,4),
    ESTIMATEDCOST NUMBER(38,4),
    PRIMARY KEY (PARTID)
);

-- Orange Tables
CREATE TABLE Bicycle (
    SERIALNUMBER NUMBER(38,0),
    MODELID NUMBER,
    PAINTID NUMBER(38, 0),
    FRAMESIZE NUMBER,
    PRIMARY KEY (SERIALNUMBER),
    CONSTRAINT Model_FK FOREIGN KEY (MODELID) REFERENCES Model(MODELID),
    CONSTRAINT PaintID FOREIGN KEY (PAINTID) REFERENCES Paint(PAINTID)
);


CREATE TABLE Customer (
    CUSTOMERID NUMBER(38,0),
    FIRSTNAME VARCHAR2(50),
    LASTNAME VARCHAR2(50),
    PHONE VARCHAR2(50),
    ADDRESSID NUMBER(38, 0),
    PRIMARY KEY (CUSTOMERID),
    CONSTRAINT CustAddr_FK FOREIGN KEY (ADDRESSID) REFERENCES Address(ADDRESSID)
);

CREATE TABLE Store (
    STOREID NUMBER(38,0),
    STORENAME VARCHAR2(50),
    PHONE VARCHAR2(50),
    ADDRESSID NUMBER(38,0),
    PRIMARY KEY (STOREID),
    CONSTRAINT StoreAddr_FK FOREIGN KEY (ADDRESSID) 
    REFERENCES Address(ADDRESSID)
);

CREATE TABLE Employee (
    EMPLOYEEID NUMBER(38,0),
    FIRSTNAME VARCHAR2(50),
    LASTNAME VARCHAR2(50),
    HOMEPHONE VARCHAR2(50),
    ADDRESSID NUMBER(38, 0),
    HIREDATE DATE,
    RELEASEDATE DATE, 
    PRIMARY KEY (EMPLOYEEID),
    CONSTRAINT EmpAddr_FK FOREIGN KEY (ADDRESSID) REFERENCES Address(ADDRESSID)
);

-- White Tables
CREATE TABLE Component (
    COMPONENTID NUMBER(38,0),
    BICYCLESERIALNUMBER NUMBER(38,0),
    EMPLOYEEID NUMBER(38,0),
    PARTID NUMBER(38,0),
    QUANTITY NUMBER(38,0),
    COST NUMBER(38,4),
    DATEINSTALLED DATE,
    CONSTRAINT CompSN_FK FOREIGN KEY (BICYCLESERIALNUMBER) REFERENCES Bicycle(SERIALNUMBER),
    CONSTRAINT CompEmp_FK FOREIGN KEY (EMPLOYEEID) REFERENCES Employee(EMPLOYEEID),
    CONSTRAINT CompPart_FK FOREIGN KEY (PARTID) REFERENCES Part(PARTID)
);

CREATE TABLE Purchase (
    PURCHASEID NUMBER(38,0),
    BICYCLESERIALNUMBER NUMBER(38,0),
    CUSTOMERID NUMBER(38,0),
    STOREID NUMBER(38,0),
    EMPLOYEEID NUMBER(38,0),
    LISTPRICE NUMBER(38, 4),
    SALEPRICE NUMBER(38,4),
    SALESTAX NUMBER(38,4),
    SHIPPRICE NUMBER(38,4),
    ORDERDATE DATE,
    STARTDATE DATE,
    SHIPDATE DATE,
    PRIMARY KEY (PURCHASEID),
    CONSTRAINT PurchaseSN_FK FOREIGN KEY (BICYCLESERIALNUMBER) REFERENCES Bicycle(SERIALNUMBER),
    CONSTRAINT Customer_FK FOREIGN KEY (CUSTOMERID) REFERENCES Customer(CUSTOMERID),
    CONSTRAINT Store_FK FOREIGN KEY (STOREID) REFERENCES Store(STOREID),
    CONSTRAINT PurchaseEmp_FK FOREIGN KEY (EMPLOYEEID) REFERENCES Employee(EMPLOYEEID)
);
COMMIT;
